{
  "tabWidth": 2,
  "semi": true,
  "singleQuote": true,
  "trailingComma": "none",
  "printWidth": 200,
  "proseWrap": "always",
  "useTabs": false,
  "bracketSpacing": true,
  "jsxBracketSameLine": false,
}